<?php

/**
 * Implements hook_block_info
 */
function why_globant_block_info() {

    $blocks = array();

    $blocks['why_globant'] = array(
        'info' => t('Why Globant'),
    );

    return $blocks;
}

/**
 * Implements hook_block_view
 */
function why_globant_block_view($delta = '') {
    $block = array();

    switch($delta) {
        case 'why_globant':
            $content = array();
            $nodes = why_globant_get_nodequeue_content('why_globant');
            $colors = array(
              'blue-base',
              'green-base',
              'lilac-base',
              'yellow-base',
              'orange-base',
            );

            foreach ($nodes as $key => $node) {
                // Get background image
                if ($node->field_imagen_fondo) {
                    $bk_image = theme('image', array(
                        'path'        => $node->field_imagen_fondo[LANGUAGE_NONE][0]['uri'],
                        'alt'         => $node->title,
                        'attributes'  => array(
                            'class' => 'bkg-image'
                        )
                    ));
                }
                // Get images related with the content
                $images = array();
                if ($node->field_imagenes[LANGUAGE_NONE]) {
                    foreach ($node->field_imagenes[LANGUAGE_NONE] as $index => $image) {
                        $images[$index]['image'] = theme('image', array(
                            'path'        => $image['uri'],
                            'alt'         => $image['alt'],
                            'title'       => $image['title'],
                            'attributes'  => array(
                                'class' => 'image-display'
                            )
                        ));
                        $images[$index]['title']  = $image['title'];
                    }
                }
                // Get logos
                $logos = array();
                if ($node->field_clientes) {
                    foreach ($node->field_clientes[LANGUAGE_NONE] as $index => $image) {
                        $logos[] = theme('image', array(
                            'path'        => $image['uri'],
                            'alt'         => $image['alt'],
                            'title'       => $image['title'],
                            'attributes'  => array(
                                'class' => 'image-display'
                            )
                        ));
                    }
                }
                $content['nodes'][$key] = array(
                    'title'           =>  $node->title,
                    'subtitulo'       =>  $node->field_subtitulo[LANGUAGE_NONE][0]['safe_value'],
                    'description'     =>  $node->body,
                    'bk_image'        =>  $bk_image,
                    'images'          =>  $images,
                    'logos'           =>  $logos,
                    'color'           =>  $colors[$key],
                    'field_color'     =>  'color-' . str_replace('#', '', $node->field_color[LANGUAGE_NONE][0]['rgb']),
                );
            }

            $block['content'] = theme('why_globant_block', $content);
            break;
    }

    return $block;
}

/**
 * Implements hook_theme()
 */
function why_globant_theme() {
    return array(
        'why_globant_block' => array(
            'variables' => array(),
            'template'  => 'templates/why-globant-block'
        )
    );
}
/**
 * Return nodes from nodequeue by its machinename
 * @param $nodequeue_name Nodequeue machine name
 * @return array
 */
function why_globant_get_nodequeue_content($nodequeue_name) {

    $nodequeue = nodequeue_load_queue_by_name($nodequeue_name);
    $nodes = nodequeue_load_nodes($nodequeue->qid, false, 0, false);

    return $nodes;
}

