<?php

/*
 * Implements hook_block_info()
 */
function search_positions_block_info() {

    $blocks['search_positions'] = array(
        'info' => t('Search Positions'),
    );

    return $blocks;
}

/*
 * Implements hook_block_view()
 */
function search_positions_block_view($delta = '') {
    $block = array();

    switch($delta) {
        case 'search_positions':

            drupal_add_library('angularjs', 'angularjs');

            $module_path = drupal_get_path('module', 'search_positions');
            drupal_add_js($module_path . '/js/search/app.js');
            // Get terms from 'Ciudades' vocabulary
            $vocabulary = taxonomy_vocabulary_machine_name_load('ciudades');
            $cities = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
            // Get terms from 'Estudios' vocabulary
            $vocabulary = taxonomy_vocabulary_machine_name_load('estudios');
            $studios = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
            // Get available positions
            $positions = node_load_multiple(array(), array('type' => 'position', 'status' => 1));
            // Get multiples location for one position
            foreach ($positions as $key => $position) {
                $location = array();
                foreach ($position->field_ciudad[LANGUAGE_NONE] as $city) {
                    $location[] = $city['tid'];
                }
                $positions[$key]->cities = implode(' ', $location);
            }

            $data = array(
              'cities'    =>  $cities,
              'studios'   =>  $studios,
              'positions' =>  $positions,
            );

            $block['content'] = theme('search_positions_block', $data);

            break;
    }

    return $block;
}

/*
 * Implements hook_theme()
 */
function search_positions_theme($existing, $type, $theme, $path) {
    return array(
        'search_positions_block' => array(
            'variables' => array(),
            'template'  => 'templates/search-positions-block'
        )
    );
}

